[package]
name = "rust-actix-web"
version = "0.1.0"
authors = ["alextanhongpin <alextan220990@gmail.com>"]

[dependencies]
actix-web = "0.7.6"
actix = "0.7.4"

serde = "1.0.78"
serde_json = "1.0.27"
serde_derive = "1.0.78"
json = "0.11.13"
